name: Main CI

on:
  push:
    branches: [main]

jobs:
  call-reusable:
    uses: sakib-codes/actions-playground/.github/workflows/reusable-node.yml@main
    with:
      node-version: "18"
      run-tests: false
    secrets:
      demo-token: ${{ secrets.DEMO_TOKEN }}

